SELECT*FROM customer LIMIT(20)

--1Q: What is the total revenue generated by male v.s female customers?
SELECT gender, SUM (purchase_amount) AS revenue
    FROM customer
    GROUP BY gender

--2Q: which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id,purchase_amount
FROM customer
WHERE discount_applied = 'Yes' AND 
purchase_amount>=(SELECT AVG (purchase_amount)FROM customer)

--3Q: which are the top 5 products with the highest average review rating?
SELECT item_purchased,
AVG (review_rating)
AS "average product rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating)
DESC LIMIT 5;
--(OR)
SELECT item_purchased,
ROUND(AVG (review_rating::NUMERIC),2)
AS "average product rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating)
DESC LIMIT 5;

--4Q compare the average purchase amounts b/w standard & express shipping?
SELECT shipping_type,
ROUND(AVG(purchase_amount),2) AS avg_purchase_amount
FROM customer
WHERE shipping_type IN('Standard','Express')
GROUP BY shipping_type;

--5Q do subscribed customers spend more? compare average spend and total revenue b/w subscribers and non-subscribers?
SELECT subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    ROUND(SUM(purchase_amount), 2) AS total_amount
FROM customer
GROUP BY subscription_status
ORDER BY total_amount, avg_spend DESC;

--6Q which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)/COUNT(*),2)
AS discount_rate FROM customer
GROUP BY item_purchased
ORDER BY discount_rate desc
limit 5;

--7Q segment customers into new ,returning, and loyal based on their total no.of previous purchases
--and show the count of each segment?
WITH customer_type AS (
    SELECT 
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)

SELECT 
    customer_segment, 
    COUNT(*) AS "number of customers"
FROM customer_type
GROUP BY customer_segment;

--8Q what are the top 3 most purchased products within each category?
with item_counts as(
select category,
item_purchased,
count (customer_id) as total_orders,
row_number() over(partition by category order by count (customer_id)desc) as item_rank
from customer
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank<=3;

--9Q are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
COUNT (customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--10Q what is the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;
